export const nutrientRequirements = {
  lifeStageGroups: [
    {
      groupName: 'Infants',
      ages: [
        {
          range: '0–6 mo',
          sex: 'any',
          nutrients: {
            'Vitamin A': 400,
            'Vitamin C': 40,
            'Vitamin E': 4,
            'Vitamin K': 2.0,
            Thiamin: 0.2,
            Riboflavin: 0.3,
            Niacin: 2,
            'Vitamin B6': 0.1,
            Folate: 65,
            'Vitamin B12': 0.4,
            'Total Fiber': 'ND',
            'Linoleic Acid': 4.4,
            'α-Linolenic Acid': 0.5,
            Protein: 9.1,
            Calcium: 200,
            Copper: 200,
            Iron: 0.27,
            Magnesium: 30,
            Manganese: 0.003,
            Phosphorus: 100,
            Selenium: 15,
            Zinc: 2,
            Potassium: 400,
          },
        },
        {
          range: '7–12 mo',
          sex: 'any',
          nutrients: {
            'Vitamin A': 500,
            'Vitamin C': 50,
            'Vitamin E': 5,
            'Vitamin K': 2.5,
            Thiamin: 0.3,
            Riboflavin: 0.4,
            Niacin: 4,
            'Vitamin B6': 0.3,
            Folate: 80,
            'Vitamin B12': 0.5,
            'Total Fiber': 'ND',
            'Linoleic Acid': 4.6,
            'α-Linolenic Acid': 0.5,
            Protein: 11,
            Calcium: 260,
            Copper: 220,
            Iron: 11,
            Magnesium: 75,
            Manganese: 0.6,
            Phosphorus: 275,
            Selenium: 20,
            Zinc: 3,
            Potassium: 860,
          },
        },
      ],
    },
    {
      groupName: 'Children',
      ages: [
        {
          range: '1–3 y',
          sex: 'any',
          nutrients: {
            'Vitamin A': 300,
            'Vitamin C': 15,
            'Vitamin E': 6,
            'Vitamin K': 30,
            Thiamin: 0.5,
            Riboflavin: 0.5,
            Niacin: 6,
            'Vitamin B6': 0.5,
            Folate: 150,
            'Vitamin B12': 0.9,
            'Total Fiber': 19,
            'Linoleic Acid': 7,
            'α-Linolenic Acid': 0.7,
            Protein: 13,
            Calcium: 700,
            Copper: 340,
            Iron: 7,
            Magnesium: 80,
            Manganese: 1.2,
            Phosphorus: 460,
            Selenium: 20,
            Zinc: 3,
            Potassium: 2000,
          },
        },
        {
          range: '4–8 y',
          sex: 'any',
          nutrients: {
            'Vitamin A': 400,
            'Vitamin C': 25,
            'Vitamin E': 7,
            'Vitamin K': 55,
            Thiamin: 0.6,
            Riboflavin: 0.6,
            Niacin: 8,
            'Vitamin B6': 0.6,
            Folate: 200,
            'Vitamin B12': 1.2,
            'Total Fiber': 25,
            'Linoleic Acid': 10,
            'α-Linolenic Acid': 0.9,
            Protein: 19,
            Calcium: 1000,
            Copper: 440,
            Iron: 10,
            Magnesium: 130,
            Manganese: 1.5,
            Phosphorus: 500,
            Selenium: 30,
            Zinc: 5,
            Potassium: 2300,
          },
        },
      ],
    },
    {
      groupName: 'Males',
      ages: [
        {
          range: '9–13 y',
          sex: 'male',
          nutrients: {
            'Vitamin A': 600,
            'Vitamin C': 45,
            'Vitamin E': 11,
            'Vitamin K': 60,
            Thiamin: 0.9,
            Riboflavin: 0.9,
            Niacin: 12,
            'Vitamin B6': 1.0,
            Folate: 300,
            'Vitamin B12': 1.8,
            'Total Fiber': 31,
            'Linoleic Acid': 12,
            'α-Linolenic Acid': 1.2,
            Protein: 34,
            Calcium: 1300,
            Copper: 700,
            Iron: 8,
            Magnesium: 240,
            Manganese: 1.9,
            Phosphorus: 1250,
            Selenium: 40,
            Zinc: 8,
            Potassium: 2500,
          },
        },
        {
          range: '14–18 y',
          sex: 'male',
          nutrients: {
            'Vitamin A': 900,
            'Vitamin C': 75,
            'Vitamin E': 15,
            'Vitamin K': 75,
            Thiamin: 1.2,
            Riboflavin: 1.3,
            Niacin: 16,
            'Vitamin B6': 1.3,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 38,
            'Linoleic Acid': 16,
            'α-Linolenic Acid': 1.6,
            Protein: 52,
            Calcium: 1300,
            Copper: 890,
            Iron: 11,
            Magnesium: 410,
            Manganese: 2.2,
            Phosphorus: 1250,
            Selenium: 55,
            Zinc: 11,
            Potassium: 3000,
          },
        },
        {
          range: '19–30 y',
          sex: 'male',
          nutrients: {
            'Vitamin A': 900,
            'Vitamin C': 90,
            'Vitamin E': 15,
            'Vitamin K': 120,
            Thiamin: 1.2,
            Riboflavin: 1.3,
            Niacin: 16,
            'Vitamin B6': 1.3,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 38,
            'Linoleic Acid': 17,
            'α-Linolenic Acid': 1.6,
            Protein: 56,
            Calcium: 1000,
            Copper: 900,
            Iron: 8,
            Magnesium: 400,
            Manganese: 2.3,
            Phosphorus: 700,
            Selenium: 55,
            Zinc: 11,
            Potassium: 3400,
          },
        },
        {
          range: '31–50 y',
          sex: 'male',
          nutrients: {
            'Vitamin A': 900,
            'Vitamin C': 90,
            'Vitamin E': 15,
            'Vitamin K': 120,
            Thiamin: 1.2,
            Riboflavin: 1.3,
            Niacin: 16,
            'Vitamin B6': 1.3,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 38,
            'Linoleic Acid': 17,
            'α-Linolenic Acid': 1.6,
            Protein: 56,
            Calcium: 1000,
            Copper: 900,
            Iron: 8,
            Magnesium: 420,
            Manganese: 2.3,
            Phosphorus: 700,
            Selenium: 55,
            Zinc: 11,
            Potassium: 3400,
          },
        },
        {
          range: '51–70 y',
          sex: 'male',
          nutrients: {
            'Vitamin A': 900,
            'Vitamin C': 90,
            'Vitamin E': 15,
            'Vitamin K': 120,
            Thiamin: 1.2,
            Riboflavin: 1.3,
            Niacin: 16,
            'Vitamin B6': 1.7,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 30,
            'Linoleic Acid': 14,
            'α-Linolenic Acid': 1.6,
            Protein: 56,
            Calcium: 1000,
            Copper: 900,
            Iron: 8,
            Magnesium: 420,
            Manganese: 2.3,
            Phosphorus: 700,
            Selenium: 55,
            Zinc: 11,
            Potassium: 3400,
          },
        },
        {
          range: '> 70 y',
          sex: 'male',
          nutrients: {
            'Vitamin A': 900,
            'Vitamin C': 90,
            'Vitamin E': 15,
            'Vitamin K': 120,
            Thiamin: 1.2,
            Riboflavin: 1.3,
            Niacin: 16,
            'Vitamin B6': 1.7,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 30,
            'Linoleic Acid': 14,
            'α-Linolenic Acid': 1.6,
            Protein: 56,
            Calcium: 1200,
            Copper: 900,
            Iron: 8,
            Magnesium: 420,
            Manganese: 2.3,
            Phosphorus: 700,
            Selenium: 55,
            Zinc: 11,
            Potassium: 3400,
          },
        },
      ],
    },
    {
      groupName: 'Females',
      ages: [
        {
          range: '9–13 y',
          sex: 'female',
          nutrients: {
            'Vitamin A': 600,
            'Vitamin C': 45,
            'Vitamin E': 11,
            'Vitamin K': 60,
            Thiamin: 0.9,
            Riboflavin: 0.9,
            Niacin: 12,
            'Vitamin B6': 1.0,
            Folate: 300,
            'Vitamin B12': 1.8,
            'Total Fiber': 26,
            'Linoleic Acid': 10,
            'α-Linolenic Acid': 1.0,
            Protein: 34,
            Calcium: 1300,
            Copper: 700,
            Iron: 8,
            Magnesium: 240,
            Manganese: 1.6,
            Phosphorus: 1250,
            Selenium: 40,
            Zinc: 8,
            Potassium: 2300,
          },
        },
        {
          range: '14–18 y',
          sex: 'female',
          nutrients: {
            'Vitamin A': 700,
            'Vitamin C': 65,
            'Vitamin E': 15,
            'Vitamin K': 75,
            Thiamin: 1.0,
            Riboflavin: 1.0,
            Niacin: 14,
            'Vitamin B6': 1.2,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 26,
            'Linoleic Acid': 11,
            'α-Linolenic Acid': 1.1,
            Protein: 46,
            Calcium: 1300,
            Copper: 890,
            Iron: 15,
            Magnesium: 360,
            Manganese: 1.6,
            Phosphorus: 1250,
            Selenium: 55,
            Zinc: 9,
            Potassium: 2300,
          },
        },
        {
          range: '19–30 y',
          sex: 'female',
          nutrients: {
            'Vitamin A': 700,
            'Vitamin C': 75,
            'Vitamin E': 15,
            'Vitamin K': 90,
            Thiamin: 1.1,
            Riboflavin: 1.1,
            Niacin: 14,
            'Vitamin B6': 1.3,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 25,
            'Linoleic Acid': 12,
            'α-Linolenic Acid': 1.1,
            Protein: 46,
            Calcium: 1000,
            Copper: 900,
            Iron: 18,
            Magnesium: 310,
            Manganese: 1.8,
            Phosphorus: 700,
            Selenium: 55,
            Zinc: 8,
            Potassium: 2600,
          },
        },
        {
          range: '31–50 y',
          sex: 'female',
          nutrients: {
            'Vitamin A': 700,
            'Vitamin C': 75,
            'Vitamin E': 15,
            'Vitamin K': 90,
            Thiamin: 1.1,
            Riboflavin: 1.1,
            Niacin: 14,
            'Vitamin B6': 1.3,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 25,
            'Linoleic Acid': 12,
            'α-Linolenic Acid': 1.1,
            Protein: 46,
            Calcium: 1000,
            Copper: 900,
            Iron: 18,
            Magnesium: 320,
            Manganese: 1.8,
            Phosphorus: 700,
            Selenium: 55,
            Zinc: 8,
            Potassium: 2600,
          },
        },
        {
          range: '51–70 y',
          sex: 'female',
          nutrients: {
            'Vitamin A': 700,
            'Vitamin C': 75,
            'Vitamin E': 15,
            'Vitamin K': 90,
            Thiamin: 1.1,
            Riboflavin: 1.1,
            Niacin: 14,
            'Vitamin B6': 1.5,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 21,
            'Linoleic Acid': 11,
            'α-Linolenic Acid': 1.1,
            Protein: 46,
            Calcium: 1200,
            Copper: 900,
            Iron: 8,
            Magnesium: 320,
            Manganese: 1.8,
            Phosphorus: 700,
            Selenium: 55,
            Zinc: 8,
            Potassium: 2600,
          },
        },
        {
          range: '> 70 y',
          sex: 'female',
          nutrients: {
            'Vitamin A': 700,
            'Vitamin C': 75,
            'Vitamin E': 15,
            'Vitamin K': 90,
            Thiamin: 1.1,
            Riboflavin: 1.1,
            Niacin: 14,
            'Vitamin B6': 1.5,
            Folate: 400,
            'Vitamin B12': 2.4,
            'Total Fiber': 21,
            'Linoleic Acid': 11,
            'α-Linolenic Acid': 1.1,
            Protein: 46,
            Calcium: 1200,
            Copper: 900,
            Iron: 8,
            Magnesium: 320,
            Manganese: 1.8,
            Phosphorus: 700,
            Selenium: 55,
            Zinc: 8,
            Potassium: 2600,
          },
        },
      ],
    },
  ],
  Pregnancy: [
    {
      range: '14–18 y',
      sex: 'female',
      nutrients: {
        'Vitamin A': 750,
        'Vitamin C': 80,
        'Vitamin E': 15,
        'Vitamin K': 75,
        Thiamin: 1.4,
        Riboflavin: 1.4,
        Niacin: 18,
        'Vitamin B6': 1.9,
        Folate: 600,
        'Vitamin B12': 2.6,
        'Total Fiber': 28,
        'Linoleic Acid': 13,
        'α-Linolenic Acid': 1.4,
        Protein: 71,
        Calcium: 1300,
        Copper: 1000,
        Iron: 27,
        Magnesium: 400,
        Manganese: 2.0,
        Phosphorus: 1250,
        Selenium: 60,
        Zinc: 12,
        Potassium: 2600,
      },
    },
    {
      range: '19–30 y',
      sex: 'female',
      nutrients: {
        'Vitamin A': 770,
        'Vitamin C': 85,
        'Vitamin E': 15,
        'Vitamin K': 90,
        Thiamin: 1.4,
        Riboflavin: 1.4,
        Niacin: 18,
        'Vitamin B6': 1.9,
        Folate: 600,
        'Vitamin B12': 2.6,
        'Total Fiber': 28,
        'Linoleic Acid': 13,
        'α-Linolenic Acid': 1.4,
        Protein: 71,
        Calcium: 1000,
        Copper: 1000,
        Iron: 27,
        Magnesium: 350,
        Manganese: 2.0,
        Phosphorus: 700,
        Selenium: 60,
        Zinc: 11,
        Potassium: 2900,
      },
    },
    {
      range: '31–50 y',
      sex: 'female',
      nutrients: {
        'Vitamin A': 770,
        'Vitamin C': 85,
        'Vitamin E': 15,
        'Vitamin K': 90,
        Thiamin: 1.4,
        Riboflavin: 1.4,
        Niacin: 18,
        'Vitamin B6': 1.9,
        Folate: 600,
        'Vitamin B12': 2.6,
        'Total Fiber': 28,
        'Linoleic Acid': 13,
        'α-Linolenic Acid': 1.4,
        Protein: 71,
        Calcium: 1000,
        Copper: 1000,
        Iron: 27,
        Magnesium: 360,
        Manganese: 2.0,
        Phosphorus: 700,
        Selenium: 60,
        Zinc: 11,
        Potassium: 2900,
      },
    },
  ],
  Lactation: [
    {
      range: '14–18 y',
      sex: 'female',
      nutrients: {
        'Vitamin A': 1200,
        'Vitamin C': 115,
        'Vitamin E': 19,
        'Vitamin K': 75,
        Thiamin: 1.4,
        Riboflavin: 1.6,
        Niacin: 17,
        'Vitamin B6': 2.0,
        Folate: 500,
        'Vitamin B12': 2.8,
        'Total Fiber': 29,
        'Linoleic Acid': 13,
        'α-Linolenic Acid': 1.3,
        Protein: 71,
        Calcium: 1300,
        Copper: 1300,
        Iron: 10,
        Magnesium: 360,
        Manganese: 2.6,
        Phosphorus: 1250,
        Selenium: 70,
        Zinc: 13,
        Potassium: 2500,
      },
    },
    {
      range: '19–30 y',
      sex: 'female',
      nutrients: {
        'Vitamin A': 1300,
        'Vitamin C': 120,
        'Vitamin E': 19,
        'Vitamin K': 90,
        Thiamin: 1.4,
        Riboflavin: 1.6,
        Niacin: 17,
        'Vitamin B6': 2.0,
        Folate: 500,
        'Vitamin B12': 2.8,
        'Total Fiber': 29,
        'Linoleic Acid': 13,
        'α-Linolenic Acid': 1.3,
        Protein: 71,
        Calcium: 1000,
        Copper: 1300,
        Iron: 9,
        Magnesium: 310,
        Manganese: 2.6,
        Phosphorus: 700,
        Selenium: 70,
        Zinc: 12,
        Potassium: 2800,
      },
    },
    {
      range: '31–50 y',
      sex: 'female',
      nutrients: {
        'Vitamin A': 1300,
        'Vitamin C': 120,
        'Vitamin E': 19,
        'Vitamin K': 90,
        Thiamin: 1.4,
        Riboflavin: 1.6,
        Niacin: 17,
        'Vitamin B6': 2.0,
        Folate: 500,
        'Vitamin B12': 2.8,
        'Total Fiber': 29,
        'Linoleic Acid': 13,
        'α-Linolenic Acid': 1.3,
        Protein: 71,
        Calcium: 1000,
        Copper: 1300,
        Iron: 9,
        Magnesium: 320,
        Manganese: 2.6,
        Phosphorus: 700,
        Selenium: 70,
        Zinc: 12,
        Potassium: 2800,
      },
    },
  ],
};
